version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile
    image: techdomov-eshop
    container_name: app
    ports:
      - "9000:9000"
    volumes:
      - /opt/techdomov-ecommerce:/var/www
    depends_on:
      - db
    networks:
      laravel:
        ipv4_address: 10.89.0.5
  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: elinkx
      MYSQL_ROOT_PASSWORD: Zelio_6236
      MYSQL_USER: marty
      MYSQL_PASSWORD: Zelio_6236
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      laravel:
        ipv4_address: 10.89.0.2
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./deployment/nginx:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    networks:
      laravel:
        ipv4_address: 10.89.0.4
volumes:
  mysql-data:
networks:
  laravel:
    external: true
